local_costmap:
  local_costmap:
    ros__parameters:
      voxel_layer:
        observation_sources: scan yolo_obstacles
        yolo_obstacles:
          topic: yolo_obstacles
          max_obstacle_height: 2.0
          min_obstacle_height: 0.0
          clearing: false
          marking: true
          data_type: PointCloud2
          obstacle_max_range: 4.0
          obstacle_min_range: 0.0

global_costmap:
  global_costmap:
    ros__parameters:
      obstacle_layer:
        observation_sources: scan yolo_obstacles
        yolo_obstacles:
          topic: yolo_obstacles
          max_obstacle_height: 2.0
          min_obstacle_height: 0.0
          clearing: false
          marking: true
          data_type: PointCloud2
          obstacle_max_range: 4.0
          obstacle_min_range: 0.0
