"""State and event constants used by the monitoring server."""

from __future__ import annotations


ROBOT_IDLE = "IDLE"
ROBOT_PATROL = "PATROL"
ROBOT_INTERACTING = "INTERACTING"
ROBOT_RESERVED = "RESERVED"
ROBOT_HANDOVER_READY = "HANDOVER_READY"
ROBOT_ESCORTING = "ESCORTING"
ROBOT_WAITING_HANDOVER = "WAITING_HANDOVER"
ROBOT_RETURNING = "RETURNING"
ROBOT_EMERGENCY = "EMERGENCY"
ROBOT_ERROR = "ERROR"

ROBOT_STATES = {
    ROBOT_IDLE, ROBOT_PATROL, ROBOT_INTERACTING, ROBOT_RESERVED,
    ROBOT_HANDOVER_READY, ROBOT_ESCORTING, ROBOT_WAITING_HANDOVER,
    ROBOT_RETURNING, ROBOT_EMERGENCY, ROBOT_ERROR,
}

EVENT_FIRE = "FIRE"
EVENT_SUSPICIOUS_PERSON = "SUSPICIOUS_PERSON"
EVENT_EMERGENCY_PATIENT = "EMERGENCY_PATIENT"
EVENT_INJURED_PERSON = "INJURED_PERSON"
EVENT_LOST_ITEM = "LOST_ITEM"

EVENT_TYPES = {
    EVENT_FIRE,
    EVENT_SUSPICIOUS_PERSON,
    EVENT_EMERGENCY_PATIENT,
    EVENT_INJURED_PERSON,
    EVENT_LOST_ITEM,
}

EVENT_TYPE_ALIASES = {
    EVENT_INJURED_PERSON: EVENT_EMERGENCY_PATIENT,
}
