"""상태·타입 enum 상수 (인터페이스 정의서 §1, §4 / 계약 §3, §6).

검증 정책(절대 규칙 5): Robot State는 로봇 소유. FMS는 관측만 하며,
enum에 없는 값이 와도 거부가 아니라 **경고 로그** 후 기록한다.
"""

from __future__ import annotations

# ── Robot State (로봇 소유, IF-02로 보고) — 10종 ──────────────────────────
ROBOT_IDLE = "IDLE"
ROBOT_PATROL = "PATROL"
ROBOT_INTERACTING = "INTERACTING"
ROBOT_RESERVED = "RESERVED"
ROBOT_HANDOVER_READY = "HANDOVER_READY"
ROBOT_ESCORTING = "ESCORTING"
ROBOT_WAITING_HANDOVER = "WAITING_HANDOVER"
ROBOT_RETURNING = "RETURNING"
ROBOT_EMERGENCY = "EMERGENCY"
ROBOT_ERROR = "ERROR"

ROBOT_STATES = {
    ROBOT_IDLE, ROBOT_PATROL, ROBOT_INTERACTING, ROBOT_RESERVED,
    ROBOT_HANDOVER_READY, ROBOT_ESCORTING, ROBOT_WAITING_HANDOVER,
    ROBOT_RETURNING, ROBOT_EMERGENCY, ROBOT_ERROR,
}

# ── Mission State (FMS 단독 소유) — 9종 ──────────────────────────────────
MISSION_REQUESTED = "REQUESTED"
MISSION_ASSIGNED = "ASSIGNED"
MISSION_ESCORTING_TO_HANDOVER = "ESCORTING_TO_HANDOVER"
MISSION_HANDOVER_WAITING = "HANDOVER_WAITING"
MISSION_ESCORTING_TO_FINAL = "ESCORTING_TO_FINAL"
MISSION_COMPLETED = "COMPLETED"
MISSION_CANCELLED = "CANCELLED"
MISSION_EMERGENCY = "EMERGENCY"
MISSION_FAILED = "FAILED"

MISSION_STATES = {
    MISSION_REQUESTED, MISSION_ASSIGNED, MISSION_ESCORTING_TO_HANDOVER,
    MISSION_HANDOVER_WAITING, MISSION_ESCORTING_TO_FINAL, MISSION_COMPLETED,
    MISSION_CANCELLED, MISSION_EMERGENCY, MISSION_FAILED,
}

# ── task_type (IF-03, 4종 — PATROL 없음: 절대 규칙 8) ────────────────────
TASK_MOVE_TO_STANDBY = "MOVE_TO_STANDBY"
TASK_ESCORT_TO_HANDOVER = "ESCORT_TO_HANDOVER"
TASK_ESCORT_TO_FINAL = "ESCORT_TO_FINAL"
TASK_RETURN_TO_BASE = "RETURN_TO_BASE"

TASK_TYPES = {
    TASK_MOVE_TO_STANDBY, TASK_ESCORT_TO_HANDOVER,
    TASK_ESCORT_TO_FINAL, TASK_RETURN_TO_BASE,
}

# ── task_status (IF-02) ──────────────────────────────────────────────────
TS_ACCEPTED = "ACCEPTED"
TS_RUNNING = "RUNNING"
TS_SUCCEEDED = "SUCCEEDED"
TS_FAILED = "FAILED"
TASK_STATUS = {TS_ACCEPTED, TS_RUNNING, TS_SUCCEEDED, TS_FAILED}

# ── task_ack result ──────────────────────────────────────────────────────
ACK_ACCEPT = "ACCEPT"
ACK_REJECT = "REJECT"

# ── IF-05 event_type ─────────────────────────────────────────────────────
# 정의서 v2.1 §IF-05 는 FIRE|SUSPICIOUS_PERSON 만 명시. EMERGENCY_PATIENT 는
# 관제 카운터(긴급 환자 수) 요구로 추가한 확장 — 정의서/비전 트랙과 동기화 필요.
EVENT_FIRE = "FIRE"
EVENT_SUSPICIOUS_PERSON = "SUSPICIOUS_PERSON"
EVENT_EMERGENCY_PATIENT = "EMERGENCY_PATIENT"
EVENT_TYPES = {EVENT_FIRE, EVENT_SUSPICIOUS_PERSON, EVENT_EMERGENCY_PATIENT}

# ESCORT 계열 task (거절 규칙 §6.2: INTERACTING/ESCORTING 아니면 거절 대상)
ESCORT_TASK_TYPES = {TASK_ESCORT_TO_HANDOVER, TASK_ESCORT_TO_FINAL}
